#!/usr/bin/env bash
# Display message to infinity
# Set a variable to 1

# Loop indefinitely
while true
do
    # Display a message
    echo "To infinity and beyond"

    # Wait for 2 seconds
    sleep 2
done

