#!/usr/bin/env bash
# This script displays 'To infinity and beyond' indefinitely
# Requirement: In between each iteration of the loop, add a sleep 2

# Define a function to handle SIGTERM signal
function invincible {
  echo "I am invincible!!!"
}

# Register the invincible function to handle SIGTERM signal
trap invincible SIGTERM

# Start an infinite loop
while true
do
  echo "To infinity and beyond"
  sleep 2
done

